---
repos:
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0  # Use the latest stable version
    hooks:
      - id: hadolint
        name: Hadolint Linter
        entry: hadolint
        language: system
        files: 'Containerfile$'
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0  # Use latest stable version
    hooks:
      - id: shellcheck
        name: ShellCheck Linter
        entry: shellcheck
        language: system
        files: '\.*sh$'  # Runs on all .sh files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0  # Use the latest stable version
    hooks:
      - id: markdownlint
        name: MarkdownLint
        entry: markdownlint
        language: node
        files: '\.md$'
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0  # Use the latest stable version
    hooks:
      - id: yamllint
        name: YAML Linter
        entry: yamllint
        language: python
        files: '\.ya?ml$'
